### PR TITLE
add compilePlugins to dist/amp/worker/worker.nodom.mjs and dist/amp/worker/worker.mjs

### PR DESCRIPTION
**Pull request by erwinmombay**
Since we distribute these files as the module version ideally they should be optimized from the get go instead of optimizing them on the user side (such as the AMP library)

### CODE REVIEW

**Comment by erwinmombay** [comment]
once this new code is published, i'll update the version we're pulling from in the https://github.com/ampproject/amphtml as well as update the copy/dist code so that it now copies the correct files instead of turning the "mjs" files into ".max.js" files

**Comment by erwinmombay** [comment]
@samouri @kristoferbaxter PTAL. im not able to assign reviewers (do i need to apply for collaborator access?)

**Comment by kristoferbaxter** [comment]
https://github.com/ampproject/worker-dom/pull/882#issuecomment-661322037

We should revisit this though, it's confusing.

**Comment by erwinmombay** [comment]
this PR is super-ceded by https://github.com/ampproject/worker-dom/pull/929

**Pull request closed without merging**
