### PR TITLE
Suppress Console Messages in AMP output

### PR DESCRIPTION
**Pull request by kristoferbaxter**
Each distributed thread's code for `amp-script` integration includes additional logging information.

~~This PR removes the logging since it can impact performance.~~

This PR uses the similar to AMP logic for retaining logs (presence of `development` or `log` in `location.hash`.

Edit: Changed approach based on PR feedback.

### CODE REVIEW

**Comment by westonruter** [comment]
I thought that Renovate would have automatically opened a PR to update `worker-dom` in `amphtml` but it's actually two versions behind now:

https://github.com/ampproject/amphtml/blob/b5494ca9c9496e0ff31a1d47f09e0805c3473aa0/package.json#L22

**Comment by estherkim** [comment]
Hey @westonruter, we purposely disable renovate-bot for dependencies. https://github.com/ampproject/amphtml/blob/master/renovate.json#L13

**Comment by choumx** [comment]
I'll upgrade amphtml soon.

**Comment by rsimha** [comment]
> I thought that Renovate would have automatically opened a PR...

This was true for both `dependencies` and `devDependencies` in the past, but at some point, it was decided to restrict automatic updates to just `devDependencies`. See  https://github.com/ampproject/amphtml/pull/17394#issuecomment-412185844 and #23008.

**Pull request merged**
