### PR TITLE
Bump version with the two releases

### PR DESCRIPTION
**Pull request by samouri**

### CODE REVIEW

**Review by jridgewell — COMMENTED** [review]
You have to use `npm version 0.27.3` in order to update the `package.json` and create the appropriate git tag.

**Comment by samouri** [comment]
Are you sure `npm run release` didn't already do that for me?

**Comment by jridgewell** [comment]
Do you have local tags? `git tag`

**Comment by samouri** [comment]
> Do you have local tags? git tag

Yep! I have a git tag for 27.3

**Comment by samouri** [comment]
🏓

**Pull request merged**
